export const ADD_STUDENT = "ADD_STUDENT";
export const SELECTED_STUDENT = "SELECTED_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const SET_EDITING = "SET_EDITING";